project:
  file: WeaverDI.xcodeproj
  target:
    name: WeaverCodeGen
templates:
  - .sourcery/Templates/AutoEquatable.stencil
  - .sourcery/Templates/AutoHashable.stencil
output:
  path: Sources/WeaverCodeGen
