language: objective-c
os: osx
osx_image: xcode9.2
env:
  - TOOLCHAINS=swift
cache:
  - bundler
before_install:
  - bundle install
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J Weaver